# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e357a139aa33b4d8df7da57f0c882511d20969f0b1ad3924697b71015a5dffd939c44e69f103363ff5db14b3957f8e6c4d43afaa42a839afbb962a058389039

test:
  secret_key_base: 716d21bcd7385aebf3f77693a2bc230bb8d42382edd439d4ca4c6201b763b2cd48759a29cbeaa833be499d203a4dab35898d014ff788118c4e104728f8d4e2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
